//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
public class FibonacciEuler{
   public static void main(String [] args){
      FibonacciEuler calc = new FibonacciEuler();      
      int sum = calc.evenSum(4000000); 
      System.out.print("Sum of Fibonacci sequence whose values do not exceed four million is: " + sum);  
   }
   
   int evenSum(int max){
      int sum = 0;
      int fib1 = 0; int fib2 = 1;
      int fibVal = 0;
      boolean surpass = false; //fibVal is currently not larger than max
      while(!surpass){
         
         if(fibVal > max){
            surpass = true;
            break;
         }
         if(fibVal % 2 == 0){
            sum += fibVal;
         }
        System.out.println("Fib value: " + fibVal);
        fibVal = fib1 + fib2;
        fib1 = fib2;
        fib2 = fibVal;
      }
      return sum;
   }
}